"""add rate limit table

Revision ID: 23c81a367c3d
Revises: 857f02cbc2a9
Create Date: 2026-04-22 20:27:27.082051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c81a367c3d'
down_revision: Union[str, Sequence[str], None] = '857f02cbc2a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_entries_key'), 'rate_limit_entries', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_entries_key'), table_name='rate_limit_entries')
    op.drop_table('rate_limit_entries')
    # ### end Alembic commands ###
