"""initial schema

Revision ID: 67e8294b4267
Revises: 
Create Date: 2026-07-17 20:34:50.349310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e8294b4267'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_table('rate_limit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_entries_key'), 'rate_limit_entries', ['key'], unique=False)
    op.create_table('superuser_panel_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_superuser_panel_tokens_token_hash'), 'superuser_panel_tokens', ['token_hash'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('course_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'user_id', name='uq_course_admin')
    )
    op.create_index(op.f('ix_course_admins_course_id'), 'course_admins', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_admins_user_id'), 'course_admins', ['user_id'], unique=False)
    op.create_table('course_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('info_md', sa.Text(), nullable=False),
    sa.Column('info_html', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('max_quiz_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_versions_course_id'), 'course_versions', ['course_id'], unique=False)
    op.create_table('login_pins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pin_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_pins_user_id'), 'login_pins', ['user_id'], unique=False)
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_log_kind'), 'notification_log', ['kind'], unique=False)
    op.create_index(op.f('ix_notification_log_user_id'), 'notification_log', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['course_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'filename', name='uq_asset_version_filename')
    )
    op.create_index(op.f('ix_assets_version_id'), 'assets', ['version_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('info', sa.Text(), nullable=False),
    sa.Column('info_html', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['course_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'slug', name='uq_block_version_slug')
    )
    op.create_index(op.f('ix_blocks_version_id'), 'blocks', ['version_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('groups_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['course_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_version_id'), 'runs', ['version_id'], unique=False)
    op.create_table('student_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['course_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'version_id', name='uq_student_enrollment')
    )
    op.create_index(op.f('ix_student_enrollments_user_id'), 'student_enrollments', ['user_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_version_id'), 'student_enrollments', ['version_id'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'name', name='uq_group_run_name')
    )
    op.create_index(op.f('ix_groups_run_id'), 'groups', ['run_id'], unique=False)
    op.create_table('mini_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('assignment_md', sa.Text(), nullable=False),
    sa.Column('assignment_html', sa.Text(), nullable=False),
    sa.Column('soft_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hard_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resubmission_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('first_submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('hard_deadline IS NULL OR resubmission_deadline IS NULL OR hard_deadline <= resubmission_deadline', name='ck_mini_project_hard_le_resubmission'),
    sa.CheckConstraint('soft_deadline IS NULL OR hard_deadline IS NULL OR soft_deadline <= hard_deadline', name='ck_mini_project_soft_le_hard'),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'block_id', name='uq_mini_project_run_block')
    )
    op.create_index(op.f('ix_mini_projects_block_id'), 'mini_projects', ['block_id'], unique=False)
    op.create_index(op.f('ix_mini_projects_run_id'), 'mini_projects', ['run_id'], unique=False)
    op.create_index('ix_mini_projects_run_published', 'mini_projects', ['run_id', 'is_published'], unique=False)
    op.create_table('run_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'filename', name='uq_run_asset_run_filename')
    )
    op.create_index(op.f('ix_run_assets_run_id'), 'run_assets', ['run_id'], unique=False)
    op.create_table('run_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'user_id', name='uq_run_teacher')
    )
    op.create_index(op.f('ix_run_teachers_run_id'), 'run_teachers', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_teachers_user_id'), 'run_teachers', ['user_id'], unique=False)
    op.create_table('sequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'slug', name='uq_sequence_block_slug')
    )
    op.create_index(op.f('ix_sequences_block_id'), 'sequences', ['block_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('content_html', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('script_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequences.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence_id', 'slug', name='uq_item_sequence_slug')
    )
    op.create_index(op.f('ix_items_sequence_id'), 'items', ['sequence_id'], unique=False)
    op.create_table('run_asset_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_asset_id', sa.Integer(), nullable=False),
    sa.Column('mini_project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mini_project_id'], ['mini_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_asset_id'], ['run_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_asset_references_mini_project_id'), 'run_asset_references', ['mini_project_id'], unique=False)
    op.create_index(op.f('ix_run_asset_references_run_asset_id'), 'run_asset_references', ['run_asset_id'], unique=False)
    op.create_table('run_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'user_id', name='uq_run_student')
    )
    op.create_index(op.f('ix_run_students_group_id'), 'run_students', ['group_id'], unique=False)
    op.create_index(op.f('ix_run_students_run_id'), 'run_students', ['run_id'], unique=False)
    op.create_index(op.f('ix_run_students_user_id'), 'run_students', ['user_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mini_project_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('submission_number', sa.Integer(), nullable=False),
    sa.Column('submitted_by', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('is_late', sa.Boolean(), nullable=False),
    sa.Column('is_resubmission', sa.Boolean(), nullable=False),
    sa.CheckConstraint('file_size > 0', name='ck_submission_file_size_positive'),
    sa.CheckConstraint('submission_number >= 1', name='ck_submission_number_positive'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mini_project_id'], ['mini_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mini_project_id', 'group_id', 'submission_number', name='uq_submission_number')
    )
    op.create_index(op.f('ix_submissions_group_id'), 'submissions', ['group_id'], unique=False)
    op.create_index('ix_submissions_latest', 'submissions', ['mini_project_id', 'group_id', 'submission_number'], unique=False)
    op.create_index(op.f('ix_submissions_mini_project_id'), 'submissions', ['mini_project_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('evaluated_by', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('feedback_file', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("result = 'accepted' OR feedback_file IS NOT NULL", name='ck_evaluation_feedback_file_required'),
    sa.CheckConstraint("result IN ('rejected', 'major_revision', 'minor_revision', 'accepted')", name='ck_evaluation_result_enum'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name='ck_evaluation_score_range'),
    sa.ForeignKeyConstraint(['evaluated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('text_md', sa.Text(), nullable=False),
    sa.Column('text_html', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('explanation_md', sa.Text(), nullable=True),
    sa.Column('explanation_html', sa.Text(), nullable=True),
    sa.Column('correct_numeric', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('precision', sa.Integer(), nullable=True),
    sa.Column('correct_text', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_item_id'), 'questions', ['item_id'], unique=False)
    op.create_table('user_item_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('is_covered', sa.Boolean(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('last_visited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_answers', sa.JSON(), nullable=True),
    sa.Column('last_score_correct', sa.Integer(), nullable=True),
    sa.Column('last_score_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_user_item_state')
    )
    op.create_index(op.f('ix_user_item_states_item_id'), 'user_item_states', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_item_states_user_id'), 'user_item_states', ['user_id'], unique=False)
    op.create_table('answer_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_options_question_id'), 'answer_options', ['question_id'], unique=False)
    op.create_table('asset_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('info_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['info_version_id'], ['course_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_references_asset_id'), 'asset_references', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_references_info_version_id'), 'asset_references', ['info_version_id'], unique=False)
    op.create_index(op.f('ix_asset_references_item_id'), 'asset_references', ['item_id'], unique=False)
    op.create_index(op.f('ix_asset_references_question_id'), 'asset_references', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_references_question_id'), table_name='asset_references')
    op.drop_index(op.f('ix_asset_references_item_id'), table_name='asset_references')
    op.drop_index(op.f('ix_asset_references_info_version_id'), table_name='asset_references')
    op.drop_index(op.f('ix_asset_references_asset_id'), table_name='asset_references')
    op.drop_table('asset_references')
    op.drop_index(op.f('ix_answer_options_question_id'), table_name='answer_options')
    op.drop_table('answer_options')
    op.drop_index(op.f('ix_user_item_states_user_id'), table_name='user_item_states')
    op.drop_index(op.f('ix_user_item_states_item_id'), table_name='user_item_states')
    op.drop_table('user_item_states')
    op.drop_index(op.f('ix_questions_item_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_submissions_mini_project_id'), table_name='submissions')
    op.drop_index('ix_submissions_latest', table_name='submissions')
    op.drop_index(op.f('ix_submissions_group_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_run_students_user_id'), table_name='run_students')
    op.drop_index(op.f('ix_run_students_run_id'), table_name='run_students')
    op.drop_index(op.f('ix_run_students_group_id'), table_name='run_students')
    op.drop_table('run_students')
    op.drop_index(op.f('ix_run_asset_references_run_asset_id'), table_name='run_asset_references')
    op.drop_index(op.f('ix_run_asset_references_mini_project_id'), table_name='run_asset_references')
    op.drop_table('run_asset_references')
    op.drop_index(op.f('ix_items_sequence_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_sequences_block_id'), table_name='sequences')
    op.drop_table('sequences')
    op.drop_index(op.f('ix_run_teachers_user_id'), table_name='run_teachers')
    op.drop_index(op.f('ix_run_teachers_run_id'), table_name='run_teachers')
    op.drop_table('run_teachers')
    op.drop_index(op.f('ix_run_assets_run_id'), table_name='run_assets')
    op.drop_table('run_assets')
    op.drop_index('ix_mini_projects_run_published', table_name='mini_projects')
    op.drop_index(op.f('ix_mini_projects_run_id'), table_name='mini_projects')
    op.drop_index(op.f('ix_mini_projects_block_id'), table_name='mini_projects')
    op.drop_table('mini_projects')
    op.drop_index(op.f('ix_groups_run_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_student_enrollments_version_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_user_id'), table_name='student_enrollments')
    op.drop_table('student_enrollments')
    op.drop_index(op.f('ix_runs_version_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_blocks_version_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_assets_version_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_notification_log_user_id'), table_name='notification_log')
    op.drop_index(op.f('ix_notification_log_kind'), table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index(op.f('ix_login_pins_user_id'), table_name='login_pins')
    op.drop_table('login_pins')
    op.drop_index(op.f('ix_course_versions_course_id'), table_name='course_versions')
    op.drop_table('course_versions')
    op.drop_index(op.f('ix_course_admins_user_id'), table_name='course_admins')
    op.drop_index(op.f('ix_course_admins_course_id'), table_name='course_admins')
    op.drop_table('course_admins')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_superuser_panel_tokens_token_hash'), table_name='superuser_panel_tokens')
    op.drop_table('superuser_panel_tokens')
    op.drop_index(op.f('ix_rate_limit_entries_key'), table_name='rate_limit_entries')
    op.drop_table('rate_limit_entries')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
