"""add user item states

Revision ID: c849511cd92b
Revises: 23c81a367c3d
Create Date: 2026-04-23 19:12:13.238996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c849511cd92b'
down_revision: Union[str, Sequence[str], None] = '23c81a367c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_item_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('is_covered', sa.Boolean(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=False),
    sa.Column('last_visited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_answers', sa.JSON(), nullable=True),
    sa.Column('last_score_correct', sa.Integer(), nullable=True),
    sa.Column('last_score_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_user_item_state')
    )
    op.create_index(op.f('ix_user_item_states_item_id'), 'user_item_states', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_item_states_user_id'), 'user_item_states', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_item_states_user_id'), table_name='user_item_states')
    op.drop_index(op.f('ix_user_item_states_item_id'), table_name='user_item_states')
    op.drop_table('user_item_states')
    # ### end Alembic commands ###
