"""add_assets_and_references

Revision ID: ce0cfee6ac72
Revises: c849511cd92b
Create Date: 2026-04-25 09:05:16.811261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0cfee6ac72'
down_revision: Union[str, Sequence[str], None] = 'c849511cd92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['course_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'filename', name='uq_asset_version_filename')
    )
    op.create_index(op.f('ix_assets_version_id'), 'assets', ['version_id'], unique=False)
    op.create_table('asset_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'item_id', name='uq_asset_reference')
    )
    op.create_index(op.f('ix_asset_references_asset_id'), 'asset_references', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_references_item_id'), 'asset_references', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_references_item_id'), table_name='asset_references')
    op.drop_index(op.f('ix_asset_references_asset_id'), table_name='asset_references')
    op.drop_table('asset_references')
    op.drop_index(op.f('ix_assets_version_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
